# Generated by Django 6.0.3 on 2026-06-29 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='E', max_length=1)),
                ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_movimentacao', models.DateTimeField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('camisa_tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='catalogo.camisatamanho')),
            ],
        ),
    ]
