# Generated by Django 6.0.3 on 2026-06-29 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('tipo', models.CharField(choices=[('C', 'Casa'), ('F', 'Fora')], default='C', max_length=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('oculto', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camisa',
                'verbose_name_plural': 'Camisas',
            },
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, unique=True)),
                ('oculto', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inicio', models.PositiveSmallIntegerField()),
                ('ano_fim', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('N', 'Nacional'), ('S', 'Seleção'), ('E', 'Europeia')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='CamisaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arquivo', models.CharField(choices=[('I', 'Imagem'), ('V', 'Video')], default='I', max_length=1)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('arquivo', models.FileField(upload_to='camisas/')),
                ('camisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='catalogo.camisa')),
            ],
            options={
                'verbose_name': 'Camisa Media',
                'verbose_name_plural': 'Camisas Media',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='camisa',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camisas', to='catalogo.clube'),
        ),
        migrations.AddField(
            model_name='camisa',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camisas', to='catalogo.temporada'),
        ),
        migrations.CreateModel(
            name='CamisaTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.PositiveSmallIntegerField(default=0)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra-Grande')], max_length=3)),
                ('oculto', models.BooleanField(default=False)),
                ('camisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='catalogo.camisa')),
            ],
            options={
                'verbose_name': 'Camisa Tamanho',
                'verbose_name_plural': 'Camisas Tamanho',
                'constraints': [models.UniqueConstraint(fields=('camisa', 'tamanho'), name='unique_camisa_tamanho')],
            },
        ),
    ]
