# Generated by Django 6.0.3 on 2026-04-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('tamanho', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco_venda', models.FloatField()),
            ],
        ),
    ]
